# Generated by Django 3.0.5 on 2020-05-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='containertype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='containertype',
            name='function',
            field=models.CharField(default='', max_length=32),
        ),
    ]
