# Generated by Django 3.0.5 on 2020-05-12 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('container', '0002_auto_20200511_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='container',
            name='child',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='container.Container'),
        ),
        migrations.AlterField(
            model_name='container',
            name='archived',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='container',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='container.Container'),
        ),
    ]
