# Generated by Django 3.0.5 on 2020-05-12 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('container', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('archived', models.BooleanField(default=False)),
                ('container', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.DO_NOTHING, to='container.Container')),
            ],
        ),
    ]
