# Generated by Django 3.0.5 on 2020-05-13 04:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('container', '0006_auto_20200512_2239'),
        ('item', '0002_auto_20200511_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='container',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='container.Container'),
        ),
    ]
